const express=require("express")
const router=express.Router()
const ConsultantController=require("../Controller/ConsultantController")
const authController = require("../Controller/authController")
const verifyJWT=require("../middleware/verifyJWT")
router.get("/",verifyJWT,ConsultantController.getAllConsultant)
router.get("/:_id",verifyJWT,ConsultantController.getConsultantByID)
router.post("/", authController.register)
router.delete("/:_id",verifyJWT, ConsultantController.deleteConsultant)
//router.put("/work-schedule", verifyJWT,ConsultantController.updateWorkSchedule)
router.put("/:_id",verifyJWT,ConsultantController.updateConsultant)
module.exports=router
