const express=require("express")
const router=express.Router()
const WeeklyReportController=require("../Controller/WeeklyReportController")
const verifyJWT=require("../middleware/verifyJWT")
router.use(verifyJWT)
router.get("/",WeeklyReportController.getAllWeeklyReport)
router.get("/date/:weeklyDate",WeeklyReportController.getWeeklyReportsByDate)
router.get("/:_id",WeeklyReportController.getWeeklyReportByID)
router.put("/:_id",WeeklyReportController.updateWeeklyReport)
router.delete("/", WeeklyReportController.deleteWeeklyReport)
router.post("/",WeeklyReportController.addWeeklyReport)
module.exports=router