const express=require("express")
const router=express.Router()
const WeeklyReportController=require("../Controller/WeeklyReportController")
const verifyJWT=require("../middleware/verifyJWT")
router.use(verifyJWT)
router.get("/",WeeklyReportController.getAllWeeklyReport)
router.get("/stats",WeeklyReportController.getWeeklyReportStats)
router.get("/date/:weekStartDate",WeeklyReportController.getWeeklyReportsByDate)
router.get("/:_id",WeeklyReportController.getWeeklyReportByID)
router.put("/:_id",WeeklyReportController.updateWeeklyReport)
router.put("/:_id/daily/:dailyWorkId",WeeklyReportController.updateDailyWork)
router.delete("/", WeeklyReportController.deleteWeeklyReport)
router.post("/",WeeklyReportController.addWeeklyReport)
router.post("/template",WeeklyReportController.createWeeklyTemplate)
router.post("/:_id/daily",WeeklyReportController.addDailyWork)
module.exports=router