require ("dotenv").config()
const express=require("express")
const cors=require("cors")
const corsOptions=require("./config/corsOptions")
const connectDB=require("./config/dbConn")
const { default: mongoose } = require("mongoose")
const PORT=process.env.PORT||7001
const app=express()
connectDB()
app.use(cors(corsOptions))
app.use(express.json())
app.use(express.static("public"))
app.use("/api/Consultant",require("./routes/ConsultantRoute"))
app.use("/api/Kindergarten",require("./routes/KindergartenRoute"))
app.use("/api/Task",require("./routes/TaskRoute"))
app.use("/api/WeeklyReport",require("./routes/WeeklyReportRoute"))
mongoose.connection.once("open",()=>{
    console.log("connected to mongoDB")
    app.listen(PORT,()=>{
        console.log(`server running on port ${PORT}`)
    })
})
mongoose.connection.on("error",(err)=>{
    console.log(err)
})